### ISSUE TITLE
Please help me it is an urgent the issue regarding checkbox and radio buttons

### ISSUE THREAD

**Issue by usolfarman** [bomsn/mf-conditional-fields#11]
Hello,

The first time it works fine, but when the user adds something different that doesn't satisfy the condition in the main text field, and then adds the correct thing without reloading the page, the checkbox and radio button are hidden. For a better understanding, please take a look at the attached video.

Regards,

https://github.com/bomsn/mf-conditional-fields/assets/159136729/ae7103c5-d683-485e-b78b-a8ef7c65f5ba

**Comment by usolfarman** [comment]
see the HTML and PHP code file attached, I have created for you for testing. The same issue was produced as I have mentioned in the video.
[inline2.zip](https://github.com/bomsn/mf-conditional-fields/files/14509400/inline2.zip)

**Comment by bomsn** [comment]
Thanks will review and try to fix this next week.

**Comment by usolfarman** [comment]
OK, I am waiting but please must looking this.

**Comment by usolfarman** [comment]
Hi,
I am waiting for your response.

**Comment by bomsn** [comment]
Should be fixed now, but you also need to make sure to use the `depth` option to define how deep should the library go in showing/hiding dependent fields.

**Comment by usolfarman** [comment]
Can you please assist me with the depth? how can I set this any example

**Comment by bomsn** [comment]
Please refer to readme https://github.com/bomsn/mf-conditional-fields?tab=readme-ov-file#available-options

**Comment by usolfarman** [comment]
Additionally, the radio buttons are still not hidden. If a field is disabled, it still appears visible when its parent is dependent on another field. For example, if there is a hierarchy A -> B -> C -> D, and B is dependent on A, and D is dependent on C with the action set to 'Enable,' then D is displayed on the first load. However, when I change the value of A, D becomes hidden.

**Comment by bomsn** [comment]
You need to use the latest version, the most recent commit of this library. You also need to make the depth higher (eg; 6 or 7)

**Comment by usolfarman** [comment]
I am using the latest and the depth is set to 20 for example.

**Comment by usolfarman** [comment]
Have you checked the below?
If a field is disabled, it still appears visible when its parent is dependent on another field. For example, if there is a hierarchy A -> B -> C -> D, and B is dependent on A, and D is dependent on C with the action set to 'Enable,' then D is displayed on the first load. However, when I change the value of A, D becomes hidden.

**Comment by usolfarman** [comment]
see the attached example for the Enable/Disabled field.
[inline2.zip](https://github.com/bomsn/mf-conditional-fields/files/14556606/inline2.zip)

**Comment by usolfarman** [comment]
The Datepicker field is disabled and is dependent on the Radio Button A. If this clicks then this field is enabled and it is working fine but the issue is that in the Text Field if I type some value that is matched or not then he is hidden and if I select the radio button A then still he is not visible.

**Comment by bomsn** [comment]
The issue is now fixed in the latest commit ( Version 1.0.6 ). 

Note that even if the field is hidden, the value remains unchanged. So it may remain disabled after the parent is hidden even if it's supposed to be enabled. if you want to restore the field to the initial status after the parent field is hidden, you should unset the field value when it's hidden by setting the `unsetHidden` option to `true`

**Comment by usolfarman** [comment]
On the first load, The date picker field is showing but when adding some value then it is now hidden permanently. the UunsetHidden is true.

**Comment by bomsn** [comment]
Are you using latest version, I've tested and everything seems to be working fine on my end. It doesn't disappear when you change values.

**Comment by usolfarman** [comment]
yes, it is the latest if you want then I will share the files.

**Comment by usolfarman** [comment]
[mf-conditional-fields.zip](https://github.com/bomsn/mf-conditional-fields/files/14557716/mf-conditional-fields.zip)
See the examples inline2.php and inline3.php

**Comment by usolfarman** [comment]
Is that possible for you that if the field is action is enabled/disabled and also dependent on another child field and this child field is also dependent on another field if this child field is set to show/hide then the first page loads the enable/disable field is also hidden and if click on match/unmatched value then it is showing and enable and if it is set unmatched then it is just disabled or enables.

**Comment by bomsn** [comment]
Hello, you can write an additional rule for hiding the fied. If you are having trouble with the show/hide of the date field, you can just specify it's visibility as part of one of the rules.

**Comment by usolfarman** [comment]
OK, Thanks for the help and development of a great JS library. If there is any issue then I will let you know again.
